---
- name: DFINSTALL
  hosts: target
  gather_facts: true
  vars:
    mapr_repo: "https://package.mapr.hpe.com/releases"
    cluster_name: "{{ my_cluster_name | default('demo') }}.df.demo"
    admin_password: "mapr"

  tasks:
    - name: set uid for /sbin/unix_chkpwd
      file:
        path: /sbin/unix_chkpwd
        mode: "u+s"
      become: true
      when: ansible_facts['os_family'] == "Debian"

    - name: get mapr installer
      get_url:
        url: "{{ mapr_repo}}/installer/mapr-setup.sh"
        dest: /tmp/mapr-setup.sh
        mode: "0755"

    - stat: path=/opt/mapr/installer/bin/mapr-installer-cli
      register: installer

    - name: setup mapr installer
      command: /tmp/mapr-setup.sh -y -r "{{ mapr_repo }}"
      become: true
      when: not installer.stat.exists

    - name: get available disks
      shell: |
        export DISKS=$(fdisk -l | grep 'Disk /dev/' | grep -v loop | cut -d' ' -f2 | tr -d :)
        export PARTS=$(fdisk -l | grep -e '^/dev/[a-z0-9]' | cut -d' ' -f1)
        for d in ${DISKS}; do if [[ "${PARTS}" != "$d"* ]] ; then echo $d; fi; done
      register: mapr_disks
      args:
        executable: /bin/bash
      become: true

    - name: copy ssh key file
      copy:
        src: "{{ inventory_dir }}/temp.pem"
        dest: "{{ ansible_user_dir }}/key.pem"
        mode: "0600"

    - name: get host public IP
      shell: "curl http://ifconfig.me"
      register: public_ip

    - set_fact:
        stanza_file: |
          environment:
            mapr_core_version: 7.1.0
          config:
            hosts:
              {{ groups['target'] | map ('extract', hostvars, 'ansible_fqdn') | to_nice_yaml | indent(4) }}
            mapr_external: {{ groups['target'] | map ('extract', hostvars, 'ansible_fqdn') | first }}:{{ public_ip.stdout }}
            ssh_id: {{ ansible_user_id }}
            ssh_key_file: {{ ansible_user_dir }}/key.pem
            cluster_name: {{ cluster_name }}
            cluster_admin_id: mapr
            cluster_admin_password: {{ admin_password }}
            db_admin_user: root
            db_admin_password: {{ admin_password }}
            log_admin_password: {{ admin_password }}
            metrics_ui_admin_password: {{ admin_password }}
            enable_encryption_at_rest: true
            license_type: M7
            mep_version: 9.0.0
            disks:
              {{ mapr_disks.stdout_lines | to_nice_yaml | indent(4) }}
            disk_format: true
            disk_stripe: 1
            services:
              template-05-converged:
              mapr-mysql:
              mapr-hivemetastore:
                database:
                  create: true
                  name: hive
                  user: hive
                  password: {{ admin_password }}
              mapr-grafana:
                enabled: true
              mapr-opentsdb:
                enabled: true
              mapr-collectd:
              mapr-fluentd:
              mapr-kibana:
                enabled: true
              mapr-elasticsearch:
                enabled: true
              mapr-data-access-gateway:
              mapr-mastgateway:
              mapr-airflow:
                enabled: true
              mapr-nifi:
                enabled: true
              mapr-zeppelin:
                enabled: true

    - name: stanza
      copy:
        dest: /tmp/mapr.stanza
        content: "{{ stanza_file }}"

    - name: wait for Installer
      wait_for:
        port: 9443

    - name: install started - this will take a while
      shell: "echo y | sudo /opt/mapr/installer/bin/mapr-installer-cli install -nv -t /tmp/mapr.stanza"
      register: install_run
      failed_when:
        - install_run.rc != 0
        - "'Install is not required' not in install_run.stderr"

    - name: copy the license
      copy: src="{{ inventory_dir }}/LatestDemoLicense-M7.txt" dest="/tmp/LatestDemoLicense-M7.txt" mode="0644"
      ignore_errors: true

    - name: nifi version
      shell: "ls -d /opt/mapr/nifi/nifi-*"
      register: nifi_path

    - name: update nifi for proxied access (ie, aws public ip)
      ansible.builtin.lineinfile:
        path: "{{ nifi_path.stdout }}/conf/nifi.properties"
        line: "nifi.web.proxy.host={{ public_ip.stdout }}:12443"
        regex: "^nifi.web.proxy.host="
      become: true
      register: nifi_reconfigured

    - name: update nifi username and password
      shell: "{{ nifi_path.stdout }}/bin/nifi.sh set-single-user-credentials mapr mapruserwith{{ admin_password }}"

    - name: restart nifi if needed
      shell: "{{ nifi_path.stdout }}/bin/nifi.sh restart"
      become: true

    ### TODO: this shouldn't be required with the installer
    - name: configure hivemeta
      shell: |
        /opt/mapr/hive/hive-3.1.3/bin/schematool -dbType mysql -initSchema
        maprcli node services -name hivemeta -action start -nodes $(hostname -f)
      become: true

    - name: wait for MCS
      wait_for:
        port: 8443

    # - name: set public IP
    #   shell: |
    #     grep -v "MAPR_EXTERNAL" /opt/mapr/conf/env_override.sh | tee /opt/mapr/conf/env_override.sh
    #     echo "export MAPR_EXTERNAL={{ public_ip.stdout }}" | tee -a /opt/mapr/conf/env_override.sh
    #     /opt/mapr/server/configure.sh -R
    #   become: true

    - name: create ticket for user
      shell: "[ -f /tmp/maprticket_${UID} ] || (echo {{ admin_password }} | maprlogin password -user mapr)"

    - name: create ticket for root
      shell: "[ -f /tmp/maprticket_0 ] || (echo {{ admin_password }} | sudo maprlogin password -user mapr)"

    - name: install mapr license
      shell: |
        [ -f /tmp/LatestDemoLicense-M7.txt ] && maprcli license add -license /tmp/LatestDemoLicense-M7.txt -is_file true
      ignore_errors: true
      register: licensed
      failed_when:
        - licensed.rc != 0
        - "'license exists' not in licensed.stdout"

    - name: result
      debug: msg="DFINSTALL=={{ install_run.stdout_lines }}==END_DFINSTALL"
