---
- name: DFSERVICES
  hosts: target
  gather_facts: true

  tasks:
    - name: get mapr services on Ubuntu
      shell: "systemctl | grep mapr | tr -s '  ' ' ' | cut -d' ' -f{{fields}}"
      register: result
      vars:
        fields: "{{ '1,3' if ansible_facts['os_family'] == 'RedHat' else '2,4' }}"

    - debug: msg="DFSERVICES=={{ result.stdout_lines }}==END_DFSERVICES"
